sudo: required
dist: trusty

os:
  - linux
  - osx

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libpcap-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/dupes/libpcap; fi

cache:
  apt: true

script:
  - autoreconf -iv > build.log 2>&1 || (cat build.log && exit 1)
  - ./configure > build.log 2>&1 || (cat build.log && exit 1)
  - make > build.log 2>&1 || (cat build.log && exit 1)
  - make dist > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make test
